steps:
  # API
  - name: "gcr.io/cloud-builders/docker"
    id: api-docker-build
    args:
      - "build"
      - "--tag=${_API_IMAGE}"
      - "."
    dir: api
  - name: "gcr.io/cloud-builders/docker"
    id: api-docker-push
    args:
      - "push"
      - "${_API_IMAGE}"
  # apps
  - name: "hashicorp/terraform"
    id: terraform-apply-apps
    dir: infra/deployment/terraform/apps
    script: |
      terraform init -backend-config=bucket=$TFSTATE_BUCKET

      terraform apply --auto-approve
    env:
      - "TFSTATE_BUCKET=${_TFSTATE_BUCKET}"
      - "TF_VAR_org_id=${_ORG_ID}"
      - "TF_VAR_all_users_ingress_tag_value_id=${_ALL_USERS_INGRESS_TAG_VALUE_ID}"
      - "TF_VAR_project_id=${PROJECT_ID}"
      - "TF_VAR_region=${_REGION}"
      - "TF_VAR_doc_ai_region=${_DOC_AI_REGION}"
      - "TF_VAR_api_image=${_API_IMAGE}"
      - "TF_VAR_api_sa_email=${_API_SA_EMAIL}"
      - "TF_VAR_api_domain_name=${_API_DOMAIN_NAME}"
options:
  logging: CLOUD_LOGGING_ONLY
